# 파일 규격 버전을 정의 -> 보통 '3.8'을 많이 사용함
# Docker Compose V2 이상에서는 'version' 필드가 선택 사항이지만, 명시적으로 작성하는 것이 좋음
version: '3.8'

# 실행하려는 컨테이너들을 '서비스'라는 단위로 묶어 정의
services:
  # 서비스의 이름을 'web' -> 원하는 이름으로 변경 가능
  web:
    # 'web' 서비스는 nginx의 최신 이미지를 사용
    image: nginx:latest
    
    # # 포트를 연결 <호스트 포트>:<컨테이너 포트>
    # # 내 컴퓨터(호스트)의 8080 포트로 들어오는 요청을 컨테이너의 80 포트로 전달
    # ports:
    #   - "8080:80" 내부 통신만 확인하기 위해 주석 처리

  # 보조 서비스 추가
  helper:
    # 'helper' 서비스는 가벼운 리눅스 이미지인 alpine을 사용
    image: alpine:latest
    # 컨테이너가 실행될 때 web 서비스에 ping 명령어를 4번 보내도록 설정
    command: ["ping", "-c", "4", "web"]